# Generated by Django 4.2 on 2026-03-03 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_pedido_produto_remove_pedido_tamanho_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoques', to='core.produto'),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='tamanho',
            field=models.CharField(max_length=5),
        ),
    ]
