# Generated by Django 4.2 on 2026-03-07 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_estoque_produto_alter_estoque_tamanho'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institucional',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='institucional',
            name='endereco',
        ),
        migrations.AddField(
            model_name='institucional',
            name='conteudo',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='institucional',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='institucional/'),
        ),
        migrations.CreateModel(
            name='ProdutoImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='produtos/')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='core.produto')),
            ],
        ),
    ]
