# Generated by Django 4.2 on 2026-03-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_pedido_bairro_pedido_cep_pedido_cidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.CharField(blank=True, choices=[('roupas', 'Item de Roupa'), ('comunicacao', 'Comunicação Visual')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='produto',
            name='subcategoria',
            field=models.CharField(blank=True, choices=[('gola-polo', 'Gola Polo'), ('camisa-comum', 'Camisa Comum'), ('calca', 'Calça')], default='', max_length=50),
        ),
    ]
