# Generated by Django 4.2 on 2026-03-09 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_produto_categoria_produto_subcategoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='subcategoria',
            field=models.CharField(blank=True, choices=[('gola-polo', 'Gola Polo'), ('camisa-comum', 'Camisa Comum'), ('calca', 'Calça'), ('logos', 'Logos'), ('impressoes', 'Impressões')], default='', max_length=50),
        ),
    ]
