# Generated by Django 4.2 on 2026-03-17 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_produto_subcategoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='subcategoria',
            field=models.CharField(blank=True, choices=[('gola-polo', 'Gola Polo'), ('camisa-comum', 'Camisa Comum'), ('calca', 'Calça'), ('logos', 'Logos'), ('impressoes', 'Impressões'), ('logos-acm', 'Logos ACM')], default='', max_length=50),
        ),
    ]
