# Generated by Django 4.2 on 2026-03-17 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_produto_subcategoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=200)),
                ('slogan', models.CharField(blank=True, default='', max_length=200)),
                ('ramo', models.CharField(max_length=200)),
                ('quantidade', models.IntegerField(default=1)),
                ('estilo', models.CharField(blank=True, default='', max_length=50)),
                ('paleta', models.CharField(blank=True, default='', max_length=50)),
                ('aplicacoes', models.JSONField(default=list)),
                ('referencia', models.TextField(blank=True, default='')),
                ('observacoes', models.TextField(blank=True, default='')),
                ('nome_cliente', models.CharField(blank=True, default='', max_length=200)),
                ('telefone', models.CharField(blank=True, default='', max_length=30)),
                ('email', models.CharField(blank=True, default='', max_length=200)),
                ('data_pedido', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('novo', 'Novo'), ('em_andamento', 'Em andamento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='novo', max_length=30)),
            ],
        ),
    ]
