# Generated by Django 4.2 on 2026-03-20 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_produto_subcategoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='subcategoria',
            field=models.CharField(blank=True, choices=[('gola-polo', 'Gola Polo'), ('camisa-comum', 'Camisa Comum'), ('calca', 'Calça'), ('impressoes', 'Impressões'), ('logos-acm', 'Logos ACM')], default='', max_length=50),
        ),
    ]
