# Generated by Django 4.2 on 2026-04-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_produto_subcategoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidopersonalizado',
            name='imagem1',
            field=models.ImageField(blank=True, null=True, upload_to='pedidos_personalizados/'),
        ),
        migrations.AddField(
            model_name='pedidopersonalizado',
            name='imagem2',
            field=models.ImageField(blank=True, null=True, upload_to='pedidos_personalizados/'),
        ),
        migrations.AddField(
            model_name='pedidopersonalizado',
            name='imagem3',
            field=models.ImageField(blank=True, null=True, upload_to='pedidos_personalizados/'),
        ),
        migrations.AddField(
            model_name='pedidopersonalizado',
            name='imagem4',
            field=models.ImageField(blank=True, null=True, upload_to='pedidos_personalizados/'),
        ),
        migrations.AddField(
            model_name='pedidopersonalizado',
            name='imagem5',
            field=models.ImageField(blank=True, null=True, upload_to='pedidos_personalizados/'),
        ),
    ]
