# Generated by Django 4.2 on 2026-04-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_pedidopersonalizado_imagem1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
