# Generated by Django 4.2.30 on 2026-07-28 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_frete_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='forma_pagamento',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
